### ISSUE TITLE
In ET version, the text under 'Kontakt' is in English (translation provided).

### ISSUE THREAD

**Issue by krtt** [MaxandreOgeret/lessn#58]
Current:
The contact form is not live yet but if you have anything to say you are very welcome to create an issue on GitHub.

Translation:
See kontaktivorm ei ole veel lives, aga kui sul on midagi öelda, siis oled oodatud seda tegema GitHub-is luues uue issue.

**Comment by MaxandreOgeret** [comment]
Thanks ! 🤗
